version: '3.3'
services:
    db:
        image: mysql:5.7
        volumes:
            - db_data:/var/lib/mysql 
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root@123
            MYSQL_DATABASE: wordpress
            MYSQL_USER: gopal
            MYSQL_PASSWORD: admin@123
    front:
        depends_on:
            - db 
        image: wordpress:latest
        ports:
            - "8000:80"
        restart: always 
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: gopal
            WORDPRESS_DB_PASSWORD: admin@123
            WORDPRESS_DB_NAME: wordpress
        
volumes:
    db_data: {}